config/routes.rb
TCM::Application.routes.draw do
  resources :patient_diseases

  resources :patient_symptoms

  resources :patients

  resources :disease_symptoms

  resources :symptoms

  resources :diseases

  resources :levels

  resources :part_feels

  resources :feels

  resources :parts

  resources :areas

  root 'patients#index'

end

app/models/feel.rb
class Feel < ActiveRecord::Base
  has_many :symptoms
  accepts_nested_attributes_for :symptoms ,:allow_destroy => true
  after_create :fill_symptom
  private
  def fill_symptom
    fid=self.id
    Part.all.each do |p|
      pid=p.id
      name=p.name + self.name
      Symptom.create(:name=>name,:part_id=>pid,:feel_id=>fid)
    end
  end
end

app/views/selfed/_diseases.edit.select_symptom.html.erb

<%= tts('select part , select symptom , then submit') %>
</br></br>

<%= tts('select part')%>
	<div id='select_part'>
	<% Part.all.each do |part| %>
	<%= check_box_tag 'part_ids[]', part.id, false %><%=part.name%>  
	<%end%>
  </div>
</br>

<%= tts('select symptom')%>

<%= semantic_bootstrap_nested_form_for @obj do |f| %>
	<div id='select_symptom'>
	<% @obj.symptoms.each do |symptom| %>
	<%= check_box_tag 'disease[symptom_ids][]', symptom.id, true %><%=symptom.name%>
	<% end %>
  </div>  
  <%= button_submit(f) %>
<% end %>

app/views/selfed/_diseases.edit.type_symptom.html.erb

<%= semantic_bootstrap_nested_form_for @obj do |f| %>
  <%= f.inputs do %>
 		<%= f.text_field :tokens, "data-pre" => @obj.symptoms.to_json %>		      
  <% end %>
  <%= button_submit(f) %>  
<% end %>

app/views/selfed/_diseases.show.symptom.html.erb
  <% @obj.symptoms.each do |sym| %>
  <%= sym.name %></br>
  <% end %>


app/views/selfed/_patients.edit.select_symptom.html.erb

<%= tts('select part , select symptom , then submit') %>
</br></br>

<%= tts('select part')%>
	<div id='select_part'>
	<% Part.all.each do |part| %>
	<%= check_box_tag 'part_ids[]', part.id, false %><%=part.name%>  
	<%end%>
  </div>
</br>

<%= tts('select symptom')%>

<%= semantic_bootstrap_nested_form_for @obj do |f| %>
	<div id='select_symptom'>
	<% @obj.symptoms.each do |symptom| %>
	<%= check_box_tag 'patient[symptom_ids][]', symptom.id, true %><%=symptom.name%>
	<% end %>
  </div>  
  <%= button_submit(f) %>
<% end %>

app/views/selfed/_patients.edit.symptom.html.erb

Customized file
<%= semantic_bootstrap_nested_form_for @obj do |f| %>
  <%= f.inputs do %>
    <%= f_input(f,'parts:c','part',{:collection=>Part.all}) %>   	 
  <% end %>
<% end %>
<%= semantic_bootstrap_nested_form_for @obj do |f| %>
  <%= f.inputs do %>
    <%= f_input(f,'symptoms:c','symptom') %>    	 
  <% end %>
  <%= button_submit(f) %>
<% end %>

app/views/selfed/_patients.edit.type_symptom.html.erb

<%= semantic_bootstrap_nested_form_for @obj do |f| %>
  <%= f.inputs do %>
 		<%= f.text_field :tokens, "data-pre" => @obj.symptoms.to_json %>		      
  <% end %>
  <%= button_submit(f) %>  
<% end %>

app/views/selfed/_patients.show.symptom.html.erb
<strong><%= tt('disease') %></strong>:</br>
  <% Disease.by_patient(@obj.id).uniq.each do |disease| %>
  <%= disease.name %></br>
  <% end %>
</br></br>
<strong><%= tt('symptom') %></strong>:</br> 
  <% @obj.symptoms.each do |sym| %>
  <%= sym.name %></br>
  <% end %>


app/views/selfed/_patients0.edit.symptom.html.erb

Individual file
<%= semantic_bootstrap_nested_form_for @obj do |f| %>
  <%= f.inputs do %>
    <%= f_input(f,'symptoms:c','symptoms',{:collection=>Symptom.by_part(2)}) %>
  <% end %>

  <%= button_submit(f) %>
<% end %>